# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171128_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploads',
            new_name='Document',
        ),
    ]
